/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas.usuarios;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Prenda;
import com.mycompany.domainclasses.Publicacion;
import com.mycompany.domainclasses.Usuario;
import com.mycompany.vistas.admin.PrendasForm;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import jnafilechooser.api.JnaFileChooser;


public class CreatePrendaForm extends javax.swing.JFrame {

    
    private byte[] fotoCargadaBytes;
    private Publicacion publicacion;
    private Usuario usuarioLogueado;
    private HomeUsuarios homeUsuarios;
    private PrendasForm prendasForm;
    /**
     * Creates new form CreatePrendaForm
     */
    
    public CreatePrendaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public CreatePrendaForm(Usuario usuarioLogueado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioLogueado = usuarioLogueado;
        
        // Si no se le manda publicacion se obtiene la default
        cargarPublicacionDefault();
    }
    
    public CreatePrendaForm(Publicacion publicacion, Usuario usuarioLogueado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.publicacion = publicacion;
        this.usuarioLogueado = usuarioLogueado;
    }
    
    public CreatePrendaForm(Publicacion publicacion, Usuario usuarioLogueado, PrendasForm prendasForm) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.publicacion = publicacion;
        this.usuarioLogueado = usuarioLogueado;
        this.prendasForm = prendasForm;
    }
    
    public CreatePrendaForm(Usuario usuarioLogueado, HomeUsuarios homeUsuarios) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuarioLogueado = usuarioLogueado;
        this.homeUsuarios = homeUsuarios;
        // Si no se le manda publicacion se obtiene la default
        cargarPublicacionDefault();
    }

    private void cargarPublicacionDefault() {

        ArrayList<Publicacion> publicaciones = (ArrayList<Publicacion>) WebServiceManager.obtenerPublicaciones();

        // Filtramos por la publicacion default de ese usuario
        Publicacion publicacionDefault = publicaciones.stream()
                .filter(publicacion -> publicacion.getIdUsuario() == this.usuarioLogueado.getIdUsuario() && publicacion.getTitulo().equals("DEFAULT"))
                .findFirst()
                .orElse(null);

        if (publicacionDefault != null) {
            this.publicacion = publicacionDefault;
        } else {
            JOptionPane.showMessageDialog(null, "No se encontro la publicacion default del usuario");
            this.dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        containerTittle3 = new com.mycompany.vistas.RoundedPanel(20);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldNombre = new RoundedTextField(20);
        jLabel6 = new javax.swing.JLabel();
        fieldTipo = new RoundedTextField(20);
        jLabel7 = new javax.swing.JLabel();
        btnSelectFoto = new javax.swing.JButton();
        panelFoto = new org.edisoncor.gui.panel.PanelImage();
        btnAddPrenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        containerTittle3.setBackground(new java.awt.Color(255, 226, 198));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Agregar prenda");

        javax.swing.GroupLayout containerTittle3Layout = new javax.swing.GroupLayout(containerTittle3);
        containerTittle3.setLayout(containerTittle3Layout);
        containerTittle3Layout.setHorizontalGroup(
            containerTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        containerTittle3Layout.setVerticalGroup(
            containerTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTittle3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 51, 0));
        jLabel5.setText("Nombre de la prenda");

        fieldNombre.setBackground(new java.awt.Color(237, 237, 237));
        fieldNombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fieldNombre.setForeground(new java.awt.Color(102, 51, 0));
        fieldNombre.setText("Escribe el nombre...");
        fieldNombre.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Escribe el tipo");

        fieldTipo.setBackground(new java.awt.Color(237, 237, 237));
        fieldTipo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fieldTipo.setForeground(new java.awt.Color(102, 51, 0));
        fieldTipo.setText("Escribe el tipo...");
        fieldTipo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 51, 0));
        jLabel7.setText("Agrega una foto de la prenda");

        btnSelectFoto.setBackground(new java.awt.Color(102, 51, 0));
        btnSelectFoto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSelectFoto.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectFoto.setText("Seleccionar foto");
        btnSelectFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectFotoActionPerformed(evt);
            }
        });

        panelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/defaultImage.jpg"))); // NOI18N

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );

        btnAddPrenda.setBackground(new java.awt.Color(102, 51, 0));
        btnAddPrenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddPrenda.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrenda.setText("Agregar prenda");
        btnAddPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTittle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(btnSelectFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldTipo)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldNombre)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)))
                    .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(containerTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelectFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectFotoActionPerformed
        // TODO add your handling code here:
        
        JnaFileChooser fileChooser = new JnaFileChooser();
        if (fileChooser.showOpenDialog(this)) {
            try {
                String imagePath = fileChooser.getSelectedFile().toPath().toString();
                File foto = new File(imagePath);

                this.fotoCargadaBytes = Files.readAllBytes(foto.toPath());
                // Cargamos la foto
                this.panelFoto.setIcon(new ImageIcon(this.fotoCargadaBytes));

                this.panelFoto.revalidate();
                this.panelFoto.repaint();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar la foto seleccionada");
                System.out.println("Error al cargar la foto: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSelectFotoActionPerformed

    private void btnAddPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrendaActionPerformed
        // TODO add your handling code here:

        String nombre = this.fieldNombre.getText();
        String tipo = this.fieldTipo.getText();

        // Verificamos que los campos no esten vacios
        if (nombre.isEmpty() || tipo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llena todos los campos");
            return;
        }

        // Guardamos la prenda
        Prenda prenda = new Prenda(this.publicacion.getIdPublicacion(), nombre, tipo);
        
        if (this.fotoCargadaBytes != null) {
            prenda.setFoto(this.fotoCargadaBytes);
        }

        // Guardamos la prenda
        int idPrenda = WebServiceManager.guardarPrenda(prenda);

        if (idPrenda != -1) {
            JOptionPane.showMessageDialog(null, "Prenda guardada correctamente");
            if (this.homeUsuarios != null) this.homeUsuarios.actualizarPrendas();
            if (this.prendasForm != null) this.prendasForm.actualizarPrendas();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Error al guardar la prenda");
        }

    }//GEN-LAST:event_btnAddPrendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreatePrendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreatePrendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreatePrendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreatePrendaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreatePrendaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrenda;
    private javax.swing.JButton btnSelectFoto;
    private javax.swing.JPanel containerTittle3;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.panel.PanelImage panelFoto;
    // End of variables declaration//GEN-END:variables
}
