/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas.admin;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Comentario;
import com.mycompany.domainclasses.Publicacion;
import com.mycompany.domainclasses.Usuario;
import java.util.ArrayList;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;


public class ComentariosForm extends javax.swing.JFrame {

    private Publicacion publicacion;
    private Usuario usuarioLogueado;
    /**
     * Creates new form ComentariosForm
     */
    public ComentariosForm() {
        initComponents();
    }
    
    public ComentariosForm(Publicacion publicacion, Usuario usuarioLogueado) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.publicacion = publicacion;
        this.usuarioLogueado = usuarioLogueado;
        
        this.containerListComments.setLayout(new BoxLayout(this.containerListComments, BoxLayout.Y_AXIS));
        
        cargarComentarios();
    }
    
    private void cargarComentarios() {
        
        this.containerListComments.removeAll();

        for (Comentario comentario : this.publicacion.getComentarios()) {
            PanelComentario pComment = new PanelComentario(comentario);
            
            pComment.setSize(this.containerListComments.getWidth(), pComment.getHeight());
            
            this.containerListComments.add(pComment);
            
            // Agreagmos un rigid area para separar los comentarios
            this.containerListComments.add(Box.createVerticalStrut(10));
        }

        this.containerListComments.revalidate();
        this.containerListComments.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        containerTittle = new com.mycompany.vistas.RoundedPanel(20);
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new com.mycompany.vistas.RoundedPanel(20);
        fieldComentario = new RoundedTextField(20);
        btnAddComment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        containerListComments = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));

        containerTittle.setBackground(new java.awt.Color(255, 226, 198));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Comentarios");

        javax.swing.GroupLayout containerTittleLayout = new javax.swing.GroupLayout(containerTittle);
        containerTittle.setLayout(containerTittleLayout);
        containerTittleLayout.setHorizontalGroup(
            containerTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerTittleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(153, 153, 153))
        );
        containerTittleLayout.setVerticalGroup(
            containerTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTittleLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        fieldComentario.setBackground(new java.awt.Color(237, 237, 237));
        fieldComentario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        fieldComentario.setForeground(new java.awt.Color(102, 51, 0));
        fieldComentario.setText("Escribe tu comentario...");
        fieldComentario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        btnAddComment.setBackground(new java.awt.Color(102, 51, 0));
        btnAddComment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddComment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddComment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-enviar.png"))); // NOI18N
        btnAddComment.setText("Enviar");
        btnAddComment.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnAddComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fieldComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddComment, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddComment, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(null);

        containerListComments.setBackground(new java.awt.Color(239, 239, 239));

        javax.swing.GroupLayout containerListCommentsLayout = new javax.swing.GroupLayout(containerListComments);
        containerListComments.setLayout(containerListCommentsLayout);
        containerListCommentsLayout.setHorizontalGroup(
            containerListCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        containerListCommentsLayout.setVerticalGroup(
            containerListCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(containerListComments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(containerTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommentActionPerformed
        // TODO add your handling code here:
        String message = this.fieldComentario.getText();
        
        if (message.equals("Escribe tu comentario...")) {
            JOptionPane.showMessageDialog(null, "Escribe un comentario");
            return;
        }
        
        // Creamos el comentario
        Comentario nuevoComentario = new Comentario(this.publicacion.getIdPublicacion(), this.usuarioLogueado.getIdUsuario(), message);
        
        int idCommentario = WebServiceManager.guardarComentario(nuevoComentario);
        
        if (idCommentario == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo agregar tu comentario, intentalo mas tarde");
            return;
        }
        
        ArrayList<Comentario> comentarios = this.publicacion.getComentarios();
        comentarios.add(nuevoComentario);
        this.publicacion.setComentarios(comentarios);
        
        cargarComentarios();
    }//GEN-LAST:event_btnAddCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComentariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComentariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComentariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComentariosForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComentariosForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComment;
    private javax.swing.JPanel containerListComments;
    private javax.swing.JPanel containerTittle;
    private javax.swing.JTextField fieldComentario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
