/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.admin;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Comentario;
import com.mycompany.domainclasses.RolUsuario;
import com.mycompany.domainclasses.Usuario;
import javax.swing.JOptionPane;


public class PanelComentario extends javax.swing.JPanel {

    private Comentario comentario;
    private Usuario usuarioLogueado;
    private ComentariosForm comentariosForm;
    
    /**
     * Creates new form PanelComentario
     */
    public PanelComentario() {
        initComponents();
    }
    
    public PanelComentario(Comentario comentario, Usuario usuarioLogueado, ComentariosForm comentariosForm) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        this.comentario = comentario;
        this.comentariosForm = comentariosForm;
        cargarDatos();
    }
    
    private void cargarDatos() {
        
        if (this.usuarioLogueado.getRol() == RolUsuario.ADMIN) {
            this.bntEliminar.setVisible(true);
        } else this.bntEliminar.setVisible(false);
        
        this.textAreaComentario.setText(comentario.getContenido());
        
        // Cargamos el usuario
        Usuario usuario = WebServiceManager.obtenerUsuarioPorId(this.comentario.getIdUsuario());
        
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el usuario que realizo el comentario");
            return;
        }
        
        this.labelUsername.setText(usuario.getNombre());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaComentario = new javax.swing.JTextArea();
        bntEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        setMaximumSize(new java.awt.Dimension(400, 142));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 142));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(0, 102, 204));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-user.png"))); // NOI18N
        labelUsername.setText("Nombre de usuario");

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        textAreaComentario.setEditable(false);
        textAreaComentario.setBackground(new java.awt.Color(255, 255, 255));
        textAreaComentario.setColumns(20);
        textAreaComentario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textAreaComentario.setForeground(new java.awt.Color(102, 102, 102));
        textAreaComentario.setRows(5);
        textAreaComentario.setText("Descriipcion\n");
        textAreaComentario.setBorder(null);
        textAreaComentario.setEnabled(false);
        jScrollPane1.setViewportView(textAreaComentario);

        bntEliminar.setBackground(new java.awt.Color(153, 0, 0));
        bntEliminar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bntEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bntEliminar.setText("Eliminar");
        bntEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsername)
                    .addComponent(bntEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEliminarActionPerformed
        // TODO add your handling code here:
        
        int idComentario = WebServiceManager.eliminarComentario(this.comentario.getIdComentario());
        
        if (idComentario == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo eliminar el comentario");
            return;
        }
        
        this.comentariosForm.actualizarComentarios();
       
    }//GEN-LAST:event_bntEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTextArea textAreaComentario;
    // End of variables declaration//GEN-END:variables
}
