/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.admin;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Comentario;
import com.mycompany.domainclasses.Usuario;
import javax.swing.JOptionPane;


public class PanelComentario extends javax.swing.JPanel {

    private Comentario comentario;
    
    /**
     * Creates new form PanelComentario
     */
    public PanelComentario() {
        initComponents();
    }
    
    public PanelComentario(Comentario comentario) {
        initComponents();
        
        this.comentario = comentario;
        
        cargarDatos();
    }
    
    private void cargarDatos() {
        
        this.textAreaComentario.setText(comentario.getContenido());
        
        // Cargamos el usuario
        Usuario usuario = WebServiceManager.obtenerUsuarioPorId(this.comentario.getIdUsuario());
        
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el usuario que realizo el comentario");
            return;
        }
        
        this.labelUsername.setText(usuario.getNombre());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaComentario = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        setMaximumSize(new java.awt.Dimension(400, 142));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 142));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(0, 102, 204));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-user.png"))); // NOI18N
        labelUsername.setText("Nombre de usuario");

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        textAreaComentario.setEditable(false);
        textAreaComentario.setBackground(new java.awt.Color(255, 255, 255));
        textAreaComentario.setColumns(20);
        textAreaComentario.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textAreaComentario.setForeground(new java.awt.Color(102, 102, 102));
        textAreaComentario.setRows(5);
        textAreaComentario.setText("Descriipcion\n");
        textAreaComentario.setBorder(null);
        textAreaComentario.setEnabled(false);
        jScrollPane1.setViewportView(textAreaComentario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JTextArea textAreaComentario;
    // End of variables declaration//GEN-END:variables
}
