/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.admin;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Publicacion;
import com.mycompany.domainclasses.Reaccion;
import com.mycompany.domainclasses.RolUsuario;
import com.mycompany.domainclasses.TipoReaccion;
import com.mycompany.domainclasses.Usuario;
import com.mycompany.vistas.usuarios.CreatePrendaForm;
import com.mycompany.vistas.usuarios.HomeUsuarios;
import java.util.Base64;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PanelPublicacion extends javax.swing.JPanel {

    private Publicacion publicacion;
    private Usuario usuarioLogueado;
    private Reaccion reaccion;
    private HomeUsuarios homeUsuarios;

    /**
     * Creates new form PanelPublicacion
     */
    public PanelPublicacion() {
        initComponents();
    }

    public PanelPublicacion(Publicacion publicacion, Usuario usuarioLogueado, HomeUsuarios homeUsuarios) {
        initComponents();
        this.publicacion = publicacion;
        this.usuarioLogueado = usuarioLogueado;

        this.homeUsuarios = homeUsuarios;
        cargarDatos();
    }

    private void cargarDatos() {
        this.labelTitulo.setText(publicacion.getTitulo());
        this.textAreaDecription.setText(publicacion.getDescripcion());
        String foto64 = Base64.getEncoder().encodeToString(publicacion.getFoto());

        if (!foto64.isEmpty()) {
            this.panelFoto.setIcon(new ImageIcon(this.publicacion.getFoto()));
        }

        // Vemos si ya tiene reaccion
        Reaccion reaccionObtenida = this.publicacion.getReacciones().stream()
                .filter(r -> r.getIdUsuario() == this.usuarioLogueado.getIdUsuario())
                .findFirst()
                .orElse(null);

        if (reaccionObtenida != null) {
            this.reaccion = reaccionObtenida;
            // Asignamos el icon segun el tipo
            switch (reaccionObtenida.getTipo()) {
                case GUSTA -> this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-gusta.png")));
                case ENCANTA -> this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-encanta.png")));
                case DIVIERTE -> this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-divierte.png")));
                case SORPRENDE -> this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-sorprende.png")));
                default -> {
                }
            }
        }

        // Consultamos al usuario
        Usuario usuario = WebServiceManager.obtenerUsuarioPorId(publicacion.getIdUsuario());

        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "No se pudo obtener al usuario de la publicacion");
            return;
        }

        this.labelUsername.setText(usuario.getNombre());

        //Cargamos los coomentarios
        cargarComentarios();
        cargarPermisosBotones();

    }

    public void cargarComentarios() {
        this.btnComentarios.setText("Comentarios (" + this.publicacion.getComentarios().size() + ")");
    }
    
    private void cargarPermisosBotones() {
        this.labelOptions.setVisible(this.usuarioLogueado.getRol() == RolUsuario.ADMIN || this.usuarioLogueado.getIdUsuario() == this.publicacion.getIdUsuario());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        itemEditar = new javax.swing.JMenuItem();
        itemAddPrendas = new javax.swing.JMenuItem();
        itemDeletePost = new javax.swing.JMenuItem();
        menuReaction = new javax.swing.JPopupMenu();
        itemGusta = new javax.swing.JMenuItem();
        itemEncanta = new javax.swing.JMenuItem();
        itemDivierte = new javax.swing.JMenuItem();
        itemSorprende = new javax.swing.JMenuItem();
        panelFoto = new org.edisoncor.gui.panel.PanelImage();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDecription = new javax.swing.JTextArea();
        labelTitulo = new javax.swing.JLabel();
        containerHeader = new javax.swing.JPanel();
        labelUsername = new javax.swing.JLabel();
        labelOptions = new javax.swing.JLabel();
        btnRepost = new javax.swing.JButton();
        btnVerPrendas = new javax.swing.JButton();
        btnReaction = new javax.swing.JButton();
        btnComentarios = new javax.swing.JButton();

        itemEditar.setText("Editar publicacion");
        popupMenu.add(itemEditar);

        itemAddPrendas.setText("Agregar prendas");
        itemAddPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAddPrendasActionPerformed(evt);
            }
        });
        popupMenu.add(itemAddPrendas);

        itemDeletePost.setText("Eliminar publicacion");
        popupMenu.add(itemDeletePost);

        menuReaction.setBackground(new java.awt.Color(255, 255, 255));

        itemGusta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-gusta.png"))); // NOI18N
        itemGusta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemGusta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGustaActionPerformed(evt);
            }
        });
        menuReaction.add(itemGusta);

        itemEncanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-encanta.png"))); // NOI18N
        itemEncanta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemEncanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEncantaActionPerformed(evt);
            }
        });
        menuReaction.add(itemEncanta);

        itemDivierte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-divierte.png"))); // NOI18N
        itemDivierte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemDivierte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDivierteActionPerformed(evt);
            }
        });
        menuReaction.add(itemDivierte);

        itemSorprende.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-sorprende.png"))); // NOI18N
        itemSorprende.setToolTipText("");
        itemSorprende.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemSorprende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSorprendeActionPerformed(evt);
            }
        });
        menuReaction.add(itemSorprende);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new org.edisoncor.gui.util.DropShadowBorder());
        setMaximumSize(new java.awt.Dimension(437, 488));

        panelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/defaultImage.jpg"))); // NOI18N

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));

        textAreaDecription.setBackground(new java.awt.Color(255, 255, 255));
        textAreaDecription.setColumns(20);
        textAreaDecription.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        textAreaDecription.setForeground(new java.awt.Color(102, 102, 102));
        textAreaDecription.setRows(5);
        textAreaDecription.setText("Descriipcion\n");
        textAreaDecription.setBorder(null);
        jScrollPane1.setViewportView(textAreaDecription);

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(102, 51, 0));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Titulo pub");

        containerHeader.setBackground(new java.awt.Color(255, 255, 255));

        labelUsername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(0, 102, 204));
        labelUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-user.png"))); // NOI18N
        labelUsername.setText("Nombre de usuario");

        labelOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-options.png"))); // NOI18N
        labelOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelOptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelOptionsMouseClicked(evt);
            }
        });

        btnRepost.setBackground(new java.awt.Color(0, 102, 204));
        btnRepost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRepost.setForeground(new java.awt.Color(255, 255, 255));
        btnRepost.setText("Repostear");
        btnRepost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerHeaderLayout = new javax.swing.GroupLayout(containerHeader);
        containerHeader.setLayout(containerHeaderLayout);
        containerHeaderLayout.setHorizontalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRepost, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelOptions)
                .addContainerGap())
        );
        containerHeaderLayout.setVerticalGroup(
            containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelOptions, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRepost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        btnVerPrendas.setBackground(new java.awt.Color(102, 51, 0));
        btnVerPrendas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnVerPrendas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerPrendas.setText("Ver prendas del conjunto");
        btnVerPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPrendasActionPerformed(evt);
            }
        });

        btnReaction.setBackground(new java.awt.Color(255, 255, 255));
        btnReaction.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnReaction.setForeground(new java.awt.Color(51, 51, 51));
        btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-reaction.png"))); // NOI18N
        btnReaction.setBorder(null);
        btnReaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReactionMouseClicked(evt);
            }
        });
        btnReaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactionActionPerformed(evt);
            }
        });

        btnComentarios.setBackground(new java.awt.Color(255, 255, 255));
        btnComentarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnComentarios.setForeground(new java.awt.Color(51, 51, 51));
        btnComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-comentarios.png"))); // NOI18N
        btnComentarios.setText("Comentarios");
        btnComentarios.setBorder(null);
        btnComentarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComentariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnReaction, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerPrendas)
                        .addContainerGap())
                    .addComponent(panelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(containerHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(containerHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerPrendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComentarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnReaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelOptionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelOptionsMouseClicked
        // TODO add your handling code here:
        this.popupMenu.show(this.labelOptions, 0, this.labelOptions.getHeight());

    }//GEN-LAST:event_labelOptionsMouseClicked

    private void btnReactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactionActionPerformed
        // TODO add your handling code here:
        // Mostramos el menu
        this.menuReaction.show(this.btnReaction, 0, -this.btnReaction.getHeight());
    }//GEN-LAST:event_btnReactionActionPerformed

    private void btnReactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReactionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReactionMouseClicked

    private void itemGustaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGustaActionPerformed
        // TODO add your handling code here:
        // Guardamos la reaccion de gusta
        Reaccion reaccion = new Reaccion(this.publicacion.getIdPublicacion(), this.usuarioLogueado.getIdUsuario(), TipoReaccion.GUSTA);
        
        if (this.reaccion != null) this.reaccion.setTipo(TipoReaccion.GUSTA);

        int idReaccion = this.reaccion != null ? WebServiceManager.actualizarReaccion(this.reaccion) : WebServiceManager.guardarReaccion(reaccion);

        if (idReaccion == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar la reaccion, intentalo mas tarde");
            return;
        }

        // Cambiamos el icono
        this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-gusta.png")));
    }//GEN-LAST:event_itemGustaActionPerformed

    private void itemEncantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEncantaActionPerformed
        // TODO add your handling code here:
        // Guardamos la reaccion de encanta
        Reaccion reaccion = new Reaccion(this.publicacion.getIdPublicacion(), this.usuarioLogueado.getIdUsuario(), TipoReaccion.ENCANTA);
        
        if (this.reaccion != null) this.reaccion.setTipo(TipoReaccion.ENCANTA);

        int idReaccion = this.reaccion != null ? WebServiceManager.actualizarReaccion(this.reaccion) : WebServiceManager.guardarReaccion(reaccion);

        if (idReaccion == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar la reaccion, intentalo mas tarde");
            return;
        }

        // Cambiamos el icono
        this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-encanta.png")));

    }//GEN-LAST:event_itemEncantaActionPerformed

    private void itemDivierteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDivierteActionPerformed
        // TODO add your handling code here:

        // Guardamos la reaccion de divierte
        Reaccion reaccion = new Reaccion(this.publicacion.getIdPublicacion(), this.usuarioLogueado.getIdUsuario(), TipoReaccion.DIVIERTE);

        if (this.reaccion != null) this.reaccion.setTipo(TipoReaccion.DIVIERTE);

        int idReaccion = this.reaccion != null ? WebServiceManager.actualizarReaccion(this.reaccion) : WebServiceManager.guardarReaccion(reaccion);

        if (idReaccion == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar la reaccion, intentalo mas tarde");
            return;
        }

        // Cambiamos el icono
        this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-divierte.png")));


    }//GEN-LAST:event_itemDivierteActionPerformed

    private void itemSorprendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSorprendeActionPerformed
        // TODO add your handling code here:

        // Guardamos la reaccion de sorprende
        Reaccion reaccion = new Reaccion(this.publicacion.getIdPublicacion(), this.usuarioLogueado.getIdUsuario(), TipoReaccion.SORPRENDE);

        if (this.reaccion != null) this.reaccion.setTipo(TipoReaccion.SORPRENDE);

        int idReaccion = this.reaccion != null ? WebServiceManager.actualizarReaccion(this.reaccion) : WebServiceManager.guardarReaccion(reaccion);

        if (idReaccion == -1) {
            JOptionPane.showMessageDialog(null, "No se pudo guardar la reaccion, intentalo mas tarde");
            return;
        }

        // Cambiamos el icono
        this.btnReaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-sorprende.png")));


    }//GEN-LAST:event_itemSorprendeActionPerformed

    private void btnComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComentariosActionPerformed
        // TODO add your handling code here:
        new ComentariosForm(publicacion, usuarioLogueado).setVisible(true);
    }//GEN-LAST:event_btnComentariosActionPerformed

    private void btnRepostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepostActionPerformed
        // TODO add your handling code here:
        new CreatePublicacionForm(usuarioLogueado, this.homeUsuarios, this.publicacion.getIdPublicacion()).setVisible(true);
    }//GEN-LAST:event_btnRepostActionPerformed

    private void itemAddPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAddPrendasActionPerformed
        // TODO add your handling code here:
        new CreatePrendaForm(this.publicacion, this.usuarioLogueado).setVisible(true);
    }//GEN-LAST:event_itemAddPrendasActionPerformed

    private void btnVerPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPrendasActionPerformed
        // TODO add your handling code here:
        
        new PrendasForm(this.publicacion, this.usuarioLogueado).setVisible(true);
    }//GEN-LAST:event_btnVerPrendasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComentarios;
    private javax.swing.JButton btnReaction;
    private javax.swing.JButton btnRepost;
    private javax.swing.JButton btnVerPrendas;
    private javax.swing.JPanel containerHeader;
    private javax.swing.JMenuItem itemAddPrendas;
    private javax.swing.JMenuItem itemDeletePost;
    private javax.swing.JMenuItem itemDivierte;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JMenuItem itemEncanta;
    private javax.swing.JMenuItem itemGusta;
    private javax.swing.JMenuItem itemSorprende;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelOptions;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPopupMenu menuReaction;
    private org.edisoncor.gui.panel.PanelImage panelFoto;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTextArea textAreaDecription;
    // End of variables declaration//GEN-END:variables
}
