/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.vistas.admin;

import javax.swing.JOptionPane;

import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Usuario;
import com.mycompany.vistas.RoundedPanel;


public class PanelUsuario extends RoundedPanel {
    
    private Usuario usuario;
    /**
     * Creates new form PanelUsuario
     */
    public PanelUsuario() {
        super(20);
        initComponents();
    }
    
    public PanelUsuario(Usuario usuario) {
        super(20);
        initComponents();
        this.usuario = usuario;
        cargarDatos();
    }
    
    private void cargarDatos() {
        this.labelCorreo.setText(this.usuario.getCorreo());
        this.labelNombre.setText(this.usuario.getNombre());
        
        // Si el usuario está bloqueado, se cambia el color del panel y se cambia el texto del botón
        if (this.usuario.isBloqueado()) {
            this.setBackground(new java.awt.Color(255, 204, 204));
            this.btnBloqeuar.setText("Desbloquear");
        } else {
            this.setBackground(new java.awt.Color(242, 242, 242));
            this.btnBloqeuar.setText("Bloquear");
        }

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCorreo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBloqeuar = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setMaximumSize(new java.awt.Dimension(516, 61));

        labelCorreo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(102, 51, 0));
        labelCorreo.setText("correo@gmail.com");

        labelNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 153, 0));
        labelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon-user.png"))); // NOI18N
        labelNombre.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Correo");

        btnBloqeuar.setBackground(new java.awt.Color(153, 51, 0));
        btnBloqeuar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnBloqeuar.setForeground(new java.awt.Color(255, 255, 255));
        btnBloqeuar.setText("Bloquear");
        btnBloqeuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloqeuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnBloqeuar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(labelNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBloqeuar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBloqeuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloqeuarActionPerformed
        // TODO add your handling code here:
        
        // Actualizamos al usuario

        if (this.usuario.isBloqueado()) {
            this.usuario.setBloqueado(false);

            this.usuario.setContrasena(null);
            
            int idUsuario = WebServiceManager.actualizarUsuario(usuario);

            if (idUsuario != -1) {
                // NOTIFICAR QUE SE ACTUALIZÓ CORRECTAMENTE
                // Actualizar el panel
                cargarDatos();
            } else {
                // NOTIFICAR QUE HUBO UN ERROR
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario");
            }

        } else {
            this.usuario.setBloqueado(true);

            int idUsuario = WebServiceManager.actualizarUsuario(usuario);

            if (idUsuario != -1) {
                // NOTIFICAR QUE SE ACTUALIZÓ CORRECTAMENTE
                // Actualizar el panel
                cargarDatos();
            } else {
                // NOTIFICAR QUE HUBO UN ERROR
                JOptionPane.showMessageDialog(null, "Error al actualizar el usuario");
            }
        }

    }//GEN-LAST:event_btnBloqeuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloqeuar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
