/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vistas.admin;

import com.google.zxing.Dimension;
import com.mycompany.dao.WebServiceManager;
import com.mycompany.domainclasses.Prenda;
import com.mycompany.domainclasses.Publicacion;
import com.mycompany.domainclasses.RolUsuario;
import com.mycompany.domainclasses.Usuario;
import com.mycompany.vistas.usuarios.CreatePrendaForm;

import java.util.ArrayList;

import javax.swing.Box;
import javax.swing.BoxLayout;


public class PrendasForm extends javax.swing.JFrame {

    private Publicacion publicacion;
    private Usuario usuarioLogueado;
    private ArrayList<Prenda> prendas;
    
    /**
     * Creates new form PrendasForm
     */
    public PrendasForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PrendasForm(Publicacion publicacion, Usuario usuarioLogueado) {
        initComponents();
        this.usuarioLogueado = usuarioLogueado;
        this.publicacion = publicacion;
        this.setLocationRelativeTo(null);
        this.labelTittle.setText("Prendas del conjunto " + this.publicacion.getTitulo());

        this.containeListPrendas.setLayout(new BoxLayout(this.containeListPrendas, BoxLayout.Y_AXIS));

        cargarPrendas();
    }
    
    private void cargarPrendas() {
        //Visibilidad de los botones si es admin o la publicacion es del usuario
        if (this.usuarioLogueado.getRol() == RolUsuario.ADMIN || this.publicacion.getIdUsuario() == this.usuarioLogueado.getIdUsuario()) {
            this.btnAddPrenda.setVisible(true);
        } else {
            this.btnAddPrenda.setVisible(false);
        }

        this.containeListPrendas.removeAll();
        this.prendas = (ArrayList<Prenda>) WebServiceManager.obtenerPrendasPorPublicacion(this.publicacion.getIdPublicacion());

        for (Prenda prenda : prendas) {
            PanelPrenda prendaItemForm = new PanelPrenda(prenda, this.publicacion, this.usuarioLogueado);
            this.containeListPrendas.add(prendaItemForm);

            // Agregamos rigid area para separar los items
            this.containeListPrendas.add(Box.createRigidArea(new java.awt.Dimension(0, 10)));
        }

        this.containeListPrendas.revalidate();
        this.containeListPrendas.repaint();
        
    }
    
    public void actualizarPrendas() {
        cargarPrendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        containerTittle3 = new com.mycompany.vistas.RoundedPanel(20);
        labelTittle = new javax.swing.JLabel();
        btnAddPrenda = new javax.swing.JButton();
        scrollPrendas = new javax.swing.JScrollPane();
        containeListPrendas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        containerTittle3.setBackground(new java.awt.Color(255, 226, 198));

        labelTittle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        labelTittle.setForeground(new java.awt.Color(255, 255, 255));
        labelTittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTittle.setText("Prendas del conjunto X");

        javax.swing.GroupLayout containerTittle3Layout = new javax.swing.GroupLayout(containerTittle3);
        containerTittle3.setLayout(containerTittle3Layout);
        containerTittle3Layout.setHorizontalGroup(
            containerTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerTittle3Layout.setVerticalGroup(
            containerTittle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerTittle3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelTittle)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnAddPrenda.setBackground(new java.awt.Color(204, 102, 0));
        btnAddPrenda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAddPrenda.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPrenda.setText("Agregar prenda");
        btnAddPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPrendaActionPerformed(evt);
            }
        });

        scrollPrendas.setBorder(null);

        containeListPrendas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containeListPrendasLayout = new javax.swing.GroupLayout(containeListPrendas);
        containeListPrendas.setLayout(containeListPrendasLayout);
        containeListPrendasLayout.setHorizontalGroup(
            containeListPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        containeListPrendasLayout.setVerticalGroup(
            containeListPrendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        scrollPrendas.setViewportView(containeListPrendas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerTittle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollPrendas))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(containerTittle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPrendas)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPrendaActionPerformed
        // TODO add your handling code here:
        
        new CreatePrendaForm(this.publicacion, this.usuarioLogueado, this).setVisible(true);
    }//GEN-LAST:event_btnAddPrendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrendasForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrendasForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPrenda;
    private javax.swing.JPanel containeListPrendas;
    private javax.swing.JPanel containerTittle3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTittle;
    private javax.swing.JScrollPane scrollPrendas;
    // End of variables declaration//GEN-END:variables
}
